routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WelcomeController')->name('welcome');
Route::resource('/vendors', 'VendorsController');
Route::resource('/filters', 'FiltersController')->except('show');
Route::resource('/brands', 'BrandsController')->except('show');
Route::resource('/sections', 'SectionsController')->except('show');
Route::resource('/categories', 'CategoriesController')->except('show');
Route::resource('products', 'ProductsController')->except('show');
Route::get('test/products', 'ProductsController@test');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::view('/design/welcome', 'design.welcome');
Route::view('/design/category-parent', 'design.category-parent');
Route::view('/design/category-child', 'design.category-child');
Route::view('/design/product', 'design.product');


//Route::get('/design/category-child', function () {
//    dd(__('countries'));
//});

Route::get('/', function () {
    return "Welcome";
})->name('home');

//end Customer

// Admin
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\LoginController@login')->name('admin.login');
Route::get('/logout', 'Auth\LoginController@logout')->name('admin.logout');

app/Models/Customer.php
<?php

namespace App\Models;

use App\User;

class Customer extends User
{
    public function details()
    {
        return $this->hasOne(CustomerDetail::class);
    }

    public function reservations()
    {
        return $this->hasMany(Reservation::class);
    }

    public function creditCards()
    {
        return $this->hasMany(CreditCard::class);
    }

}

resources/views/admin/customers/index.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="col-md-10 offset-md-2 main-interface">
        <ul class="nav directory">
            <li class="nav-item">
                <a class="nav-link">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link">Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link">Index</a>
            </li>
        </ul>
        @include('admin.layouts.notification')
        <section class="content">
            <div class="card data-table-wrapper">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h2>All Customers</h2>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-customized" id="dataTable">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Email</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Purchasing</th>
                            <th>Publish date</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($customers as $customer)
                            <tr>
                                <td>{{$customer->id}}</td>
                                <td>{{$customer->email}}</td>
                                <td>{{$customer->name}}</td>
                                <td>{{$customer->details?$customer->details->phone:null}}</td>
                                <td>{{$customer->reservations->count()}}</td>
                                <td class="numbers">{{$customer->created_at}}</td>
                                <td class="actions">
                                    <a href="{{route('admin.customers.show',['id'=>$customer->id])}}" class="editable">
                                        <i class="fas fa-sign-out-alt"></i>
                                    </a>
                                    <form action="{{route('admin.vendors.destroy',['id'=>$customer->id])}}"
                                          method="post"
                                          id="delete_row">
                                        {{csrf_field()}}
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button class="text-danger"><i class="fas fa-trash-restore"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </section>


    </div>
@endsection
@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('css/panel/data-table.css')}}">
@endsection
@section('javascript')
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>
    <script>
        $('#dataTable').DataTable({
            "order": []
        });
        $('form#delete_row').submit(function (event) {
            var confirmed = confirm('Are you sure you want to delete this Vendor? ');
            if (confirmed !== true) {
                event.preventDefault();
            }
        });
    </script>
@endsection

resources/views/admin/customers/show.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="col-md-10 offset-md-2 main-interface">
        <ul class="nav directory">
            <li class="nav-item">
                <a class="nav-link">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link">Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link">Show</a>
            </li>
        </ul>
        @include('admin.layouts.notification')
        <section class="content">
            <div class="card data-table-wrapper">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h2>Customer: {{$customer->name}}</h2>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="fields-section">
                        <div class="row">
                            <div class="col-md-2"><span class="field-name">Name</span></div>
                            <div class="col-md-4">{{$customer->name}}</div>
                            <div class="col-md-2"><span class="field-name">Email</span></div>
                            <div class="col-md-4">{{$customer->email}}</div>
                        </div>
                        @if($customer->details)
                            <div class="row">
                                <div class="col-md-2"><span class="field-name">Phone</span></div>
                                <div class="col-md-4">{{$customer->details->phone}}</div>
                                <div class="col-md-2"><span class="field-name">Address</span></div>
                                <div class="col-md-4">{{$customer->details->address}}</div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><span class="field-name">Street</span></div>
                                <div class="col-md-4">{{$customer->details->street}}</div>
                                <div class="col-md-2"><span class="field-name">City</span></div>
                                <div class="col-md-4">{{$customer->details->city}}</div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><span class="field-name">Country</span></div>
                                <div class="col-md-4">{{$customer->details->country}}</div>
                                <div class="col-md-2"><span class="field-name">Created At</span></div>
                                <div class="col-md-4">{{$customer->created_at}}</div>
                            </div>
                            @if($customer->details->hotel)
                                <div class="row">
                                    <div class="col-md-2"><span class="field-name">Hotel</span></div>
                                    <div class="col-md-4">{{$customer->details->hotel->hotel}}</div>
                                    <div class="col-md-2"><span class="field-name">Room NO</span></div>
                                    <div class="col-md-4">{{$customer->details->room_no}}</div>
                                </div>
                            @endif
                        @endif
                    </div>
                    <div class="fields-section">
                        <h2>Credit Cards</h2>
                        @foreach($customer->creditCards as $creditCard)
                            <div class="credit">
                                <div class="row">
                                    <div class="col-md-2"><span class="field-name">Name</span></div>
                                    <div class="col-md-4">{{$creditCard->name}}</div>
                                    <div class="col-md-2"><span class="field-name">Number</span></div>
                                    <div class="col-md-4">{{$creditCard->cc_no}}</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-2"><span class="field-name">Expire Date</span></div>
                                    <div class="col-md-4">{{$creditCard->cc_expire_month}}
                                        / {{$creditCard->cc_expire_year}}</div>
                                    <div class="col-md-2"><span class="field-name">CVV</span></div>
                                    <div class="col-md-4">{{$creditCard->cvv}}</div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                    <div class="fields-section">
                        <h2>Purchasing</h2>
                        @foreach($customer->reservations as $reservation)
                            <div class="reservation">
                                <div class="row">
                                    <div class="col-md-2"><span class="field-name">Purchasing NO</span></div>
                                    <div class="col-md-4">{{$reservation->unique_id}}</div>
                                    <div class="col-md-2"><span class="field-name">Total</span></div>
                                    <div class="col-md-4">{{sprintf('%.2f %s',$reservation->total,strtoupper($reservation->currency))}}</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-2"><span class="field-name">Payment Method</span></div>
                                    <div class="col-md-4">{{$reservation->payment_method}}</div>
                                    <div class="col-md-2"><span class="field-name">Payment Approval</span></div>
                                    <div class="col-md-4">{{$reservation->payment_approval?'Paid':'Not Paid'}}</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-2"><span class="field-name">Transaction Id</span></div>
                                    <div class="col-md-4">{{$reservation->transaction_id}}</div>
                                    <div class="col-md-2">
                                        <a href="{{route('admin.reservations.show',['id'=>$reservation->id])}}">
                                            MoreDetails
                                        </a>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </section>


    </div>
@endsection