routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WelcomeController')->name('welcome');
Route::resource('/vendors', 'VendorsController');
Route::resource('/filters', 'FiltersController')->except('show');
Route::resource('/brands', 'BrandsController')->except('show');
Route::resource('/sections', 'SectionsController')->except('show');
Route::resource('/categories', 'CategoriesController')->except('show');
Route::resource('products', 'ProductsController')->except('show');
Route::get('test/products', 'ProductsController@test');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::view('/design/welcome', 'design.welcome');
Route::view('/design/category-parent', 'design.category-parent');
Route::view('/design/category-child', 'design.category-child');
Route::view('/design/product', 'design.product');


//Route::get('/design/category-child', function () {
//    dd(__('countries'));
//});

Route::get('/', function () {
    return "Welcome";
})->name('home');

//end Customer

// Admin
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\LoginController@login')->name('admin.login');
Route::get('/logout', 'Auth\LoginController@logout')->name('admin.logout');

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Brand
 * @package App\Models
 * @method static Brand create(array $attributes)
 * @property string $image
 * @property string $thumb
 */
class Brand extends Model
{
    use StatusOptionalable, FilterableSearch;
    protected $fillable = [
        'en_name', 'ar_name', 'sort_order', 'status', 'image', 'thumb'
    ];
    public $count;

    public function setCount($products)
    {
        $this->count = $products;
        return $this;
    }
}

app/Http/Controllers/Admin/BrandsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\BrandsRequest;
use App\Models\Brand;
use Exception;

class BrandsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $limit = request()->get('limit') ?? 10;
        $brands = Brand::filter()->paginate($limit);
        return view('admin.brands.index', compact('brands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $brand = new Brand();
        return view('admin.brands.create', compact('brand'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BrandsRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(BrandsRequest $request)
    {
        try {
            Brand::create($request->input());
            return redirect()->route('admin.brands.index')->with('success', 'Brand has been inserted');
        } catch (Exception $e) {
            image()->rollback();
            return redirect()->back()->with('failure', $e->getMessage());
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param Brand $brand
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Brand $brand)
    {
        return view('admin.brands.edit', compact('brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BrandsRequest $request
     * @param Brand $brand
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(BrandsRequest $request, Brand $brand)
    {
        try {
            $brand->update($request->input());
            $brand->touch();
            return redirect()->route('admin.brands.index')->with('success', 'Brand has been updated');
        } catch (Exception $e) {
            return redirect()->back()->with('failure', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Brand $brand
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Brand $brand)
    {
        try {
            $brand->delete();
            return redirect()->route('admin.brands.index')->with('success', 'Brand has been deleted');
        } catch (Exception $exception) {
            return redirect()->back()->with('failure', $exception->getMessage());
        }
    }

}

resources/views/admin/brands/create.blade.php
@extends('admin.layouts.master')
@section('directory')
    <ul class="nav directory">
        <li class="nav-item">
            <a class="nav-link">Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Brands</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Creating</a>
        </li>
    </ul>
@stop
@section('content')
    <section class="content">
        <div class="card form-wrapper">
            <div class="card-header card-header-min">
                <h2>Add new Brand</h2>
                <div class="card-header-actions">
                    <button class="btn btn-success" form="basic_form">
                        <i class="las la-save"></i>
                    </button>
                    <a class="btn btn-warning" href="{{url()->previous()}}">
                        <i class="fas fa-reply-all"></i>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <form method="post" action="{{route('admin.brands.store')}}" id="basic_form" enctype="multipart/form-data">
                    @csrf
                    @include('admin.brands.partial.form')
                </form>
            </div>
        </div>

    </section>
@endsection
@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('css/panel/form.css')}}">
@endsection

resources/views/admin/brands/edit.blade.php
@extends('admin.layouts.master')
@section('content')
    @if($errors->any())
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="alert-heading">Oops! something went wrong</h4>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <section class="content">
        <div class="card form-wrapper">
            <div class="card-header">
                <div class="row">
                    <div class="col">
                        <h2>Edit brand</h2>
                    </div>
                    <div class="col text-right">
                        <button class="btn btn-success" form="basic_form"><i class="fas fa-save"></i></button>
                        <a class="btn btn-primary" href="{{URL::previous()}}"><i class="fas fa-reply-all"></i></a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post" action="{{route('admin.brands.update',compact('brand'))}}" id="basic_form"
                      enctype="multipart/form-data">
                    @csrf @method('PUT')
                    @include('admin.brands.partial.form')
                </form>
            </div>
        </div>

    </section>
@endsection
@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('css/panel/form.css')}}">
@endsection

resources/views/admin/brands/index.blade.php
@extends('admin.layouts.master')
@section('directory')
    <ul class="nav directory">
        <li class="nav-item">
            <a class="nav-link">Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Brands</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Index</a>
        </li>
    </ul>
@stop
@section('content')
    <section class="content">
        <div class="card data-table-wrapper">
            <div class="card-header card-header-min">
                <h2>All Products Brands</h2>
                <a href="{{route('admin.brands.create')}}" class="btn btn-warning addable">
                    <i class="fas fa-forward"></i> Add new brand
                </a>
            </div>
            <div class="card-body">
                <form method="get" action="{{route('admin.brands.index')}}">
                    <div class="search-form-wrapper">
                        <div class="search-form">
                            <div class="search-form-col">
                                <select name="limit" class="custom-select">
                                    <option disabled selected>Select limit</option>
                                    @foreach(paginationLimit() as $limit)
                                        @php
                                            $selectedLimit=request()->has('limit')&& request()->get('limit')===$limit?'selected':'';
                                        @endphp
                                        <option value="{{$limit}}" {{$selectedLimit}}>{{$limit}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="search-form-col">
                                <input name="criteria" class="form-control" autocomplete="off" placeholder="Search For">
                            </div>
                            <div class="search-form-col">
                                <select class="custom-select" name="status">
                                    <option disabled selected>Select Status</option>
                                    <option value="">All</option>
                                    @foreach(\App\Models\Vendor::statusOptions() as $key=>$value)
                                        <option value="{{$key}}">{{$value['status']}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <button class="btn btn-success"><i class="fas fa-filter"></i></button>
                            <button type="reset" class="btn btn-secondary" onclick="this.form.reset();">
                                <i class="fas fa-power-off"></i>
                            </button>
                        </div>
                    </div>
                </form>
                <div class="result-count">
                    <i class="lab la-adversal"></i> {{$brands->lastItem()}}/{{$brands->total()}} Brand
                </div>
                <table class="table table-striped table-min">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th class="ar-font">الاسم</th>
                        <th>Logo</th>
                        <th>Sort order</th>
                        <th>Publish date</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($brands as $brand)
                        <tr>
                            <td>{{$brand->id}}</td>
                            <td>{{$brand->en_name}}</td>
                            <td class="ar-font">{{$brand->ar_name}}</td>
                            <td class="logo-thumb"><img src="{{asset('storage/'.$brand->thumb)}}" alt="#"></td>
                            <td>{{$brand->sort_order}}</td>
                            <td class="numbers">{{$brand->created_at}}</td>
                            <td class="status">
                                <button class="btn  {{$brand->status['btn_color']}}">{{$brand->status['status']}}</button>
                            </td>
                            <td class="actions">
                                <a href="{{route('admin.brands.edit',compact('brand'))}}" class="editable">
                                    <i class="las la-edit"></i>
                                </a>
                                <form action="{{route('admin.brands.destroy',compact('brand'))}}" method="post">
                                    @csrf @method('DELETE')
                                    <button class="text-danger">
                                        <i class="las la-trash-restore"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="pagination-wrapper">
                    {{$brands->withQueryString()->links()}}
                </div>
            </div>
        </div>
    </section>
@endsection
@section('css')
    <link rel="stylesheet" href="{{asset('css/panel/table.min.css')}}">
@stop