routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WelcomeController')->name('welcome');
Route::resource('/vendors', 'VendorsController');
Route::resource('/filters', 'FiltersController')->except('show');
Route::resource('/brands', 'BrandsController')->except('show');
Route::resource('/sections', 'SectionsController')->except('show');
Route::resource('/categories', 'CategoriesController')->except('show');
Route::resource('products', 'ProductsController')->except('show');
Route::get('test/products', 'ProductsController@test');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::view('/design/welcome', 'design.welcome');
Route::view('/design/category-parent', 'design.category-parent');
Route::view('/design/category-child', 'design.category-child');
Route::view('/design/product', 'design.product');


//Route::get('/design/category-child', function () {
//    dd(__('countries'));
//});

Route::get('/', function () {
    return "Welcome";
})->name('home');

//end Customer

// Admin
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\LoginController@login')->name('admin.login');
Route::get('/logout', 'Auth\LoginController@logout')->name('admin.logout');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class Category
 * @package App\Models
 * @property integer $id
 * @property bool $has_products
 * @property Category $parents
 * @property string $en_name
 * @property string $ar_name
 * @property array $full_en_name
 * @property string $image
 * @method static Category create(array $attribute)
 * @method static Builder parentsOnly()
 * @method static Category findOrFail(int $id)
 */
class Category extends Model
{
    use FilterableSearch, StatusOptionalable;
    protected  $with = ['brands', 'filters', 'parents'];
    protected  $fillable = [
        'parent_id',
        'en_name',
        'ar_name',
        'en_slug',
        'ar_slug',
        'sort_order',
        'status',
        'image',
        'icon',
        'has_products',
    ];

    /**
     * @param $sort_order
     *
     * Setting Sort Order Column
     */
    public function setSortOrderAttribute($sort_order)
    {
        $this->attributes['sort_order'] = $sort_order ?? 0;
    }

    /**
     * @param $en_slug
     *
     * Setting English Slug Column
     */
    public function setEnSlugAttribute($en_slug)
    {
        $this->attributes['en_slug'] = Str::slug($en_slug);
    }

    /**
     * @param $ar_slug
     *
     * Setting Arabic Slug Column
     */
    public function setArSlugAttribute($ar_slug)
    {
        $this->attributes['ar_slug'] = Str::slug($ar_slug);
    }

    /**
     * @return array
     */
    public static function hasProductOptions()
    {
        return [
            0 => [
                'status' => 'Parent Category',
                'btn_color' => 'btn-warning'
            ],
            1 => [
                'status' => 'Has Products',
                'btn_color' => 'btn-success'
            ]
        ];
    }

    /**
     * @return array
     */
    public static function productOptionsOnly()
    {
        return array_map(function ($option) {
            return $option['status'];
        }, self::hasProductOptions());
    }

    public function getHasProductStatusAttribute()
    {
        return self::hasProductOptions()[$this->has_products];
    }

    public function brands()
    {
        return $this->belongsToMany(Brand::class, 'category_brand');
    }

    public function filters()
    {
        return $this->belongsToMany(Filter::class);
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function parents()
    {
        return $this->parent()->with('parents');
    }

    public function getFullEnNameAttribute()
    {
        $nameList = [$this->en_name];
        $this->extractParentsName($this, 'en_name', $nameList);
        return $nameList;
    }

    private function extractParentsName(Category $category, string $column, array &$nameList)
    {
        if (!is_null($category->parents)) {
            $nameList[] = $category->parents->{$column};
            $category->extractParentsName($category->parents, $column, $nameList);
        }
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function tags()
    {
        return $this->morphOne(MetaTag::class, 'taggable');
    }

    /**
     * @param Builder $query
     */
    public function scopeParentsOnly(Builder $query)
    {
        $query->where('has_products', '0');
    }


//    /**
//     * @param array $children
//     * @return Category[]
//     */
//    public function allChildren(&$children = [])
//    {
//        if ($this->children()->exists()) {
//            $categories = $this->children()->get()->all();
//            /**
//             * @var Category $category
//             */
//            foreach ($categories as $category) {
//                $children[] = $category;
//                $category->allChildren($children);
//            }
//        }
//        return $children;
//    }
//
//    public function allBrands(&$brands = [])
//    {
//        $brands = array_merge($brands, array_udiff($this->brands()->get()->all(), $brands, function ($brand_1, $brand_2) {
//            $id_1 = $brand_1->id;
//            $id_2 = $brand_2->id;
//            if ($id_1 == $id_2) {
//                return 0;
//            }
//            return $id_1 > $id_2 ? 1 : -1;
//        }));
//        if ($this->parent()->exists()) {
//            $this->parent()->first()->allBrands($brands);
//        }
//        return $brands;
//    }
//
//
//    public function allParents(array $parents = [])
//    {
//        $parents = array_merge($parents, [$this]);
//        if (!is_null($this->parent)) {
//            return $this->parent->allParents($parents);
//        }
//        return collect(array_reverse($parents));
//    }
//
//    public function fullName($property, $separating = " > ")
//    {
//        $fullName = [];
//        $fullName[] = $this->{$property};
//        if (!is_null($this->parent)) {
//            $fullName[] = $this->parent->fullName($property);
//        }
//        return self::joinName($fullName, $separating);
//    }
//
//    private static function joinName(array $name, $separating)
//    {
//        return implode($separating, array_reverse($name));
//    }
//
//    public static function recommendationCategories()
//    {
//        return (new static)
//            ->where('recommended', 1)
//            ->where('image', '!=', '')
//            ->orderBy('sort_order')
//            ->limit(3)
//            ->get()
//            ->all();
//    }
//
//    public static function homeCategories()
//    {
//        return (new static)
//            ->where('status', 1)
//            ->where('home', 1)
//            ->where('welcome_image', '!=', '')
//            ->orderBy('home_sort_order')
//            ->limit(2)
//            ->get()
//            ->all();
//    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Filter;
use Illuminate\Support\Carbon;
use Illuminate\Validation\ValidationException;
use Exception;

class CategoriesController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $limit = request()->get('limit') ?? 10;
        $categories = Category::filter()->paginate($limit);
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $category = new Category();
        $categories = Category::parentsOnly()->get();
        $filters = Filter::all();
        $brands = Brand::all();
        return view('admin.categories.create', compact('categories', 'category', 'filters', 'brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CategoryRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CategoryRequest $request)
    {
        try {
            Category::create($request->input('main'));
            return redirect()->route('admin.categories.index')->with('success', 'Category has been inserted');
        } catch (Exception $exception) {
            image()->rollback();
            return redirect()->back()->with('failure', $exception->getMessage())
                ->withInput($request->input());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Category $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Category $category)
    {
        $categories = Category::parentsOnly()->get();
        $filters = Filter::all();
        $brands = Brand::all();
        return view('admin.categories.edit', compact('category', 'categories', 'brands', 'filters'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryRequest $request
     * @param Category $category
     * @return \Illuminate\Http\RedirectResponse
     * @throws ValidationException
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $this->validateHasProducts($request, $category);
        try {
            $category->setUpdatedAt(Carbon::now());
            $category->update($request->input('main'));

            return redirect()->route('admin.categories.index')->with('success', 'Category has been updated');
        } catch (Exception $exception) {
            image()->rollback();
            return redirect()->back()->with('failure', $exception->getMessage())
                ->withInput($request->input());
        }

    }

    /**
     * @param CategoryRequest $request
     * @param Category $category
     * @throws ValidationException
     */
    private function validateHasProducts(CategoryRequest $request, Category $category)
    {
        if ($request->input('main.has_products') == 0 && $category->has_products && $category->products()->exists()) {
            throw ValidationException::withMessages(
                ['has_product_cant_changing' => 'this category has products inside , due you can\'t change category mode before delete related products']
            );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return \Illuminate\Http\RedirectResponse
     * @throws Exception
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('admin.categories.index')->with('success', 'Category has been deleted');
    }


}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')
@section('directory')
    <ul class="nav directory">
        <li class="nav-item">
            <a class="nav-link">Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Categories</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Create</a>
        </li>
    </ul>
@stop
@section('content')
    @if($errors->any())
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="alert-heading">Oops! something went wrong</h4>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <section class="content">
        <div class="card form-wrapper">
            @include('admin.layouts.card-header',['title'=>'Add new Category','form_id'=>'main_form'])
            <div class="card-body">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <a class="nav-item nav-link active" id="nav-category-basic-tab" data-toggle="tab"
                           href="#nav-category-basic"
                           role="tab" aria-controls="nav-category-basic" aria-selected="true">
                            Category details
                        </a>
                        <a class="nav-item nav-link" id="nav-meta-tab" data-toggle="tab" href="#nav-meta"
                           role="tab" aria-controls="nav-meta" aria-selected="false">
                            Meta Tags
                        </a>
                        <a class="nav-item nav-link" id="nav-brands-tab" data-toggle="tab" href="#nav-brands"
                           role="tab" aria-controls="nav-brands" aria-selected="false">
                            Brands
                        </a>
                        <a class="nav-item nav-link" id="nav-filters-tab" data-toggle="tab" href="#nav-filters"
                           role="tab" aria-controls="nav-filters" aria-selected="false">
                            Filters
                        </a>

                    </div>
                </nav>
                <form method="post" id="main_form" action="{{route('admin.categories.store')}}"
                      enctype="multipart/form-data">
                    @csrf
                    @include('admin.categories.partial.form')
                </form>
            </div>
        </div>

    </section>
@endsection
@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('css/panel/form.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />>
@endsection
@prepend('javascript')
    <script src="{{asset('js/jquery-2.2.3.min.js')}}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js"></script>
@endprepend

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')
@section('directory')
    <ul class="nav directory">
        <li class="nav-item">
            <a class="nav-link">Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Categories</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Edit</a>
        </li>
    </ul>
@endsection
@section('content')
    @error('has_product_cant_changing')
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="alert-heading">Oops! something went wrong</h4>
        {{$message}}
    </div>
    @enderror
    <section class="content">
        <div class="card form-wrapper">
            @include('admin.layouts.card-header',['title'=>"Update {$category->en_name}",'form_id'=>'main_form'])
            <div class="card-body">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <a class="nav-item nav-link active" id="nav-category-basic-tab" data-toggle="tab"
                           href="#nav-category-basic"
                           role="tab" aria-controls="nav-category-basic" aria-selected="true">
                            Category details
                        </a>
                        <a class="nav-item nav-link" id="nav-meta-tab" data-toggle="tab" href="#nav-meta"
                           role="tab" aria-controls="nav-meta" aria-selected="false">
                            Meta Tags
                        </a>
                        <a class="nav-item nav-link" id="nav-brands-tab" data-toggle="tab" href="#nav-brands"
                           role="tab" aria-controls="nav-brands" aria-selected="false">
                            Brands
                        </a>
                        <a class="nav-item nav-link" id="nav-filters-tab" data-toggle="tab" href="#nav-filters"
                           role="tab" aria-controls="nav-filters" aria-selected="false">
                            Filters
                        </a>

                    </div>
                </nav>
                <form method="post" id="main_form" action="{{route('admin.categories.update',compact('category'))}}"
                      enctype="multipart/form-data">
                    @csrf @method('PUT')
                    @include('admin.categories.partial.form')
                </form>
            </div>
        </div>

    </section>
@endsection
@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('css/panel/form.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>>
@endsection
@prepend('javascript')
    <script src="{{asset('js/jquery-2.2.3.min.js')}}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js"></script>
@endprepend

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')
@section('directory')
    <ul class="nav directory">
        <li class="nav-item">
            <a class="nav-link">Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Categories</a>
        </li>
        <li class="nav-item">
            <a class="nav-link">Index</a>
        </li>
    </ul>
@stop
@section('content')
    <section class="content">
        <div class="card data-table-wrapper">
            <div class="card-header card-header-min">
                <h2>All Products Categories</h2>
                <a href="{{route('admin.categories.create')}}" class="btn btn-warning addable">
                    <i class="las la-plus"></i> Add new category
                </a>

            </div>
            <div class="card-body">
                @include('admin.layouts.search-form',['route'=>route('admin.categories.index'),'options'=>\App\Models\Category::statusOptions()])
                <div class="result-count">
                    <i class="las la-filter"></i> {{$categories->lastItem()??0}}/{{$categories->total()}} Category
                </div>
                <table class="table table-striped table-min">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Category</th>
                        <th>Sort order</th>
                        <th>Status</th>
                        <th>Has Product</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <td>{{$category->id}}</td>
                            <td class="text-left">{{implode(' > ', array_reverse($category->full_en_name))}}</td>
                            <td>{{$category->sort_order}}</td>
                            <td class="status">
                                <button class="btn  {{$category->status['btn_color']}}">{{$category->status['status']}}</button>
                            </td>
                            <td class="status">
                                <button class="btn  {{$category->has_product_status['btn_color']}}">{{$category->has_product_status['status']}}</button>
                            </td>
                            <td class="actions">
                                <a href="{{route('admin.categories.edit',compact('category'))}}" class="editable">
                                    <i class="las la-edit"></i>
                                </a>
                                <form action="{{route('admin.categories.destroy',compact('category'))}}" method="post">
                                    @csrf @method('DELETE')
                                    <button class="text-danger">
                                        <i class="las la-trash-restore"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="pagination-wrapper">
                    {{$categories->withQueryString()->links()}}
                </div>
            </div>
        </div>
    </section>
@endsection
@section('css')
    <link rel="stylesheet" href="{{asset('css/panel/table.min.css')}}">
@endsection